### ISSUE TITLE
Spec doesn't specify that a Resolver MUST return an error when DID being resolved not in DIDDoc

### ISSUE THREAD

**Issue by swcurran** [decentralized-identity/didwebvh#191]
From @peacekeeper 👍 

I'm doing some experiments with portability, I tried simply copying the did.jsonl file from one location to another, without actually updating it.
I used this original DID: 

`did:webvh:QmPEQVM1JPTyrvEgBcDXwjK4TeyLGSX1PxjgyeAisdWM1p:gist.githubusercontent.com:brianorwhatever:9c4633d18eb644f7a47f93a802691626:raw`

And then copied the did.jsonl file to this DID: 

`did:webvh:QmPEQVM1JPTyrvEgBcDXwjK4TeyLGSX1PxjgyeAisdWM1p:gist.githubusercontent.com:peacekeeper:2a0e3e9b87819a38555273a3f2c5bd2c:raw`

They are both resolvable via the universal resolver, which is based on the [did:webvh TS implementation](https://github.com/decentralized-identity/didwebvh-ts):

- [https://dev.uniresolver.io/#did:webvh:QmPEQVM1JPTyrvEgBcDXwjK4TeyLGSX1PxjgyeAisdWM1p:g[…]nt.com:brianorwhatever:9c4633d18eb644f7a47f93a802691626:raw](https://dev.uniresolver.io/#did:webvh:QmPEQVM1JPTyrvEgBcDXwjK4TeyLGSX1PxjgyeAisdWM1p:g[…]nt.com:brianorwhatever:9c4633d18eb644f7a47f93a802691626:raw)
- [https://dev.uniresolver.io/#did:webvh:QmPEQVM1JPTyrvEgBcDXwjK4TeyLGSX1PxjgyeAisdWM1p:g[…]ontent.com:peacekeeper:2a0e3e9b87819a38555273a3f2c5bd2c:raw](https://dev.uniresolver.io/#did:webvh:QmPEQVM1JPTyrvEgBcDXwjK4TeyLGSX1PxjgyeAisdWM1p:g[…]ontent.com:peacekeeper:2a0e3e9b87819a38555273a3f2c5bd2c:raw)
- 
But since I didn't actually update the DID document, resolving the "new" DID actually returns exactly the same DID document as the original DID. In other words, the value of the "id" property of the DID document does not match the DID that was resolved, which I think should be an error.

**Comment by swcurran** [comment]
Thanks, @peacekeeper.  The spec outlines in the Create and Update sections that the id property in the DIDDoc MUST be the full DID, but does not mention it in the Read section.  So that needs to be fixed in the spec and in the implementations.

I'll put in a PR to the spec.  Over to @Brian Richter, @Andrew Whitehead to check the implementations.

**Comment by swcurran** [comment]
Note that the JSONL file for a DID **MAY** be sourced from anywhere -- such as a watcher.  But the **resolution** of the DID **MUST* account for the the DID being resolved and the DIDDoc that is within the log.

**Comment by andrewwhitehead** [comment]
The Python implementation resolves the first DID but not the second one, returning this instead:

```
{
  "@context": "https://w3id.org/did-resolution/v1",
  "didDocument": null,
  "didDocumentMetadata": null,
  "didResolutionMetadata": {
    "error": "invalidDid",
    "errorMessage": "Document @id mismatch",
    "contentType": "application/did+ld+json"
  }
}
```

@swcurran You might want to un-tag `@andrew`

**Comment by peacekeeper** [comment]
> The Python implementation resolves the first DID but not the second one, returning this instead:

Great..! Is the Universal Resolver did:webvh driver based on this Python implementation? If yes, would it be possible to create a new version of the Docker image? See here:

https://github.com/decentralized-identity/universal-resolver/blob/main/docker-compose.yml#L377

**Comment by swcurran** [comment]
The Universal Resolver is based on the TS implementation, so we need a fix for that, and then it will get pushed into the Universal Resolver driver.

**Comment by swcurran** [comment]
Resolved from the specification perspective. Fix in the TS implementation is in progress (or done?).

**Comment by peacekeeper** [comment]
I tried this in the Universal Resolver, and it's not fixed there yet apparently, e.g. try these:

- https://dev.uniresolver.io/#did:webvh:QmPEQVM1JPTyrvEgBcDXwjK4TeyLGSX1PxjgyeAisdWM1p:gist.githubusercontent.com:brianorwhatever:9c4633d18eb644f7a47f93a802691626:raw
- https://dev.uniresolver.io/#did:webvh:QmPEQVM1JPTyrvEgBcDXwjK4TeyLGSX1PxjgyeAisdWM1p:gist.githubusercontent.com:peacekeeper:2a0e3e9b87819a38555273a3f2c5bd2c:raw

**Comment by brianorwhatever** [comment]
@peacekeeper @swcurran the first returns the DID Doc properly and the second returns a pretty basic 404. It looks like this should be an invalid DID error though as the file exists however it has the wrong `id`?

**Comment by swcurran** [comment]
Agree on the second -- the did:doc should return a 404, as the DID doesn't match the `id` in the DIDDoc.

I'm a little confused about the second, and I see that the DID Log is at: https://gist.githubusercontent.com/peacekeeper/2a0e3e9b87819a38555273a3f2c5bd2c/raw -- but should it be at: https://gist.githubusercontent.com/peacekeeper/2a0e3e9b87819a38555273a3f2c5bd2c/raw/did.jsonl?  E.g., the `did:jsonl` appended to it?  Or is it enough that the DID Log is provided, and the ID matches the DID being resolved?

**Comment by brianorwhatever** [comment]
oh yeah good call. @peacekeeper it looks like the gist has the file name "did-scid-did-webvh" at https://gist.github.com/peacekeeper/2a0e3e9b87819a38555273a3f2c5bd2c/

It's possible if that is renamed to did.jsonl it might return `invalidDID`
